name: Build and Release Python EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # Create this file with your project dependencies
    
    - name: Build Windows EXE
      run: |
        pyinstaller --onefile --windowed main.py
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
